### ISSUE TITLE
Update routing structure for demo app

### ISSUE THREAD

**Issue by davitykale-zz** [TFC-ListProject/build-the-list#28]
Current:

/state 
/district/:districtId

Proposed:

/:state
/:state/district/:districtId

**Comment by dbolson** [comment]
@davitykale Do we have a list of the proposed endpoints?

Does this mean we would have endpoints such as

```
/va // state data
/va/districts/1 // data for Virginia district 1, not district with database id of 1
```

**Comment by davitykale-zz** [comment]
@dbolson I don't think we have a list of the proposed endpoints yet. This issue is mostly about the routing structure of the client side app. We can have API endpoints that match that, but we certainly don't have to.

**Comment by dbolson** [comment]
https://docs.google.com/document/d/1Qc1vge6xc6UVq71JIQV_zU0HS8bZmhQWcTo3SkfQELc/edit
